import torch
import torch.nn as nn

def conv_bn_relu(input_num, output_num, kernel_size = 3, padding = 1):
    return nn.Sequential(
        nn.Conv2d(input_num, output_num, kernel_size=kernel_size, padding=padding),
        nn.BatchNorm2d(output_num),
        nn.ReLU(inplace=True)
    )

class VGG(nn.Module):
    def __init__(self, model_type = 'A', input_size = (224, 224), output_size = 1000) -> None:
        super(VGG, self).__init__()
        self.model_type = model_type
        self.input_size = input_size
        self.fc1 = nn.Linear(512 * 7 * 7, 4096)
        self.fc2 = nn.Linear(4096, 4096)
        self.fc3 = nn.Linear(4096, output_size)
        self.conv3_64_bn_relu = conv_bn_relu(3, 64)
        self.conv64_64_bn_relu = conv_bn_relu(64, 64)
        self.conv64_128_bn_relu = conv_bn_relu(64, 128)
        self.conv128_128_bn_relu = conv_bn_relu(128, 128)
        self.conv128_256_bn_relu = conv_bn_relu(128, 256)
        self.conv256_256_bn_relu = conv_bn_relu(256, 256)
        self.conv256_256_1_bn_relu = conv_bn_relu(256, 256, 1)
        self.conv256_512_bn_relu = conv_bn_relu(256, 512)
        self.conv512_512_bn_relu = conv_bn_relu(512, 512)
        self.conv512_512_1_bn_relu = conv_bn_relu(512, 512, 1)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.average_pool = nn.AdaptiveAvgPool2d((7, 7))
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        if self.model_type == 'A':
            return self.forward_A(x)
        if self.model_type == 'B':
            return self.forward_B(x)
        if self.model_type == 'C':
            return self.forward_C(x)
        if self.model_type == 'D':
            return self.forward_D(x)
        if self.model_type == 'E':
            return self.forward_E(x)

    # 11
    def forward_A(self, x):
        x = self.conv3_64_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv64_128_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv128_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv256_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
        
    # 13
    def forward_B(self, x):
        x = self.conv3_64_bn_relu(x)
        x = self.conv64_64_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv64_128_bn_relu(x)
        x = self.conv128_128_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv128_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv256_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
        
    # 16
    def forward_C(self, x):
        x = self.conv3_64_bn_relu(x)
        x = self.conv64_64_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv64_128_bn_relu(x)
        x = self.conv128_128_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv128_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.conv256_256_1_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv256_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_1_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_1_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
        
    # 16 D is better than C
    def forward_D(self, x):
        x = self.conv3_64_bn_relu(x)
        x = self.conv64_64_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv64_128_bn_relu(x)
        x = self.conv128_128_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv128_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv256_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
        
    # 19
    def forward_E(self, x):
        x = self.conv3_64_bn_relu(x)
        x = self.conv64_64_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv64_128_bn_relu(x)
        x = self.conv128_128_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv128_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.conv256_256_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv256_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.conv512_512_bn_relu(x)
        x = self.maxpool(x)
        x = self.relu(x)
        x = torch.flatten(x, 1)
        x = self.fc1(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc2(x)
        x = self.dropout(x)
        x = self.relu(x)
        x = self.fc3(x)
        return x
        
# m = VGG()
# input = torch.rand((1, 3, 224, 224))
# output = m.forward(input)
